name: Docker Image 만들기

# Event : 실행되는 시점
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# 하나의 워크플로우에 1개 이상의 잡
# 잡은 병렬 수행
jobs:
  My-Deploy-Job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
          token: ${{secrets.PAT_TOKEN}}

      - name: JDK 17 설치
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Spring Project 빌드하기
        run: |
          cd ./server/
          chmod +x ./gradlew
          ./gradlew clean build -x test

      - name: Docker 이미지 만들고 Dockerhub에 푸시
        run: |
          docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
          docker build -t ${{secrets.DOCKER_REPO}}/diabet-server:latest .
          docker push ${{secrets.DOCKER_REPO}}/diabet-server:${{github.sha}}

      - name: EC2에서 이미지 pull 후, 컨테이너 실행
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_SSH_USER }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            docker rm -f $(docker ps -qa)
            docker run -d -p 8080:8080 ${{secrets.DOCKER_REPO}}/diabet-server:${{github.sha}}
